# Generated by Django 5.0.6 on 2024-09-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='bot_image',
            field=models.ImageField(blank=True, null=True, upload_to='bot_images/'),
        ),
    ]
